### ISSUE TITLE
subscription

### ISSUE THREAD

**Issue by firefly5927** [Zweihui/RxFingerPrinter#1]
兄台，我不订阅直接按压指纹，都可以去验证指纹，这是什么情况？

**Comment by Zweihui** [comment]
调用```begin()```方法后，是直接开启指纹监听的，订阅相当于Callback的作用。

**Comment by firefly5927** [comment]
我的意思是，我没有点击开启按钮，没有调用begin方法呀。

**Comment by Zweihui** [comment]
贴一下代码吧，不调用begin是不会开启的指纹监听的。

**Comment by firefly5927** [comment]
抱歉没说清楚，运行的你的demo。测试手机红米4

**Comment by Zweihui** [comment]
我是用小米note2和华为mate8测试的，都没有你说的这种情况。我这里也没有红米4，不能重现你的问题。
