### ISSUE TITLE
运行时错误

### ISSUE THREAD

**Issue by leonyan18** [Zweihui/RxFingerPrinter#3]
在多次点击开启之后会报错
publishSubject.onError(new FPerException(FINGERPRINTERS_FAILED_ERROR));//这里报错

以下是错误信息

W/System.err: io.reactivex.exceptions.UndeliverableException: zwh.com.lib.FPerException
W/System.err:     at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)
W/System.err:     at io.reactivex.subjects.PublishSubject.onError(PublishSubject.java:192)
W/System.err:     at zwh.com.lib.RxFingerPrinter$1.onAuthenticationError(RxFingerPrinter.java:113)
W/System.err:     at android.hardware.fingerprint.FingerprintManager$MyHandler.sendErrorResult(FingerprintManager.java:930)
W/System.err:     at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:878)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
W/System.err:     at android.os.Looper.loop(Looper.java:164)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6665)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
W/System.err: Caused by: zwh.com.lib.FPerException
W/System.err: 	... 9 more

**Comment by Zweihui** [comment]
已修复
